In [1]:
a = [1.0, 2.0, 1.0]

In [6]:
import torch
a= torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
points = torch.tensor([[4,2], [2,2],[1,2]])
points

tensor([[4, 2],
        [2, 2],
        [1, 2]])

In [9]:
points.shape

torch.Size([3, 2])

In [11]:
#accessing elements
points[2,1]
points[2]

tensor([1, 2])

In [14]:
#indexing tensors
l = list(range(6))
l[:]
l[1:4]
l[1:4:2]
l[1:]
l[:-3]
l[:-1]

[0, 1, 2, 3, 4]

In [15]:
#named tensor
img_t = torch.randn(3,5,5)
img_t

tensor([[[ 0.4224,  0.8528, -0.1955, -1.0366, -1.6073],
         [ 1.0373,  0.0423,  0.5899,  1.6751,  1.5429],
         [-0.5093, -2.6138, -0.1909, -1.1183,  1.1499],
         [ 0.2106, -0.1707,  0.6643,  0.7008,  0.2087],
         [-0.6802, -0.2734,  0.2218,  0.0050,  0.5888]],

        [[ 0.3365,  0.4435, -0.0616,  0.0306,  1.0136],
         [ 0.4474, -0.0524,  0.2303,  1.5914,  0.8155],
         [ 0.2044,  0.7729, -0.3294,  0.0150, -1.1176],
         [-0.8938, -0.9000,  1.6414, -0.9111,  0.9230],
         [-0.6257, -2.0653,  1.6829,  0.2602,  0.6734]],

        [[-1.7196,  0.2924,  0.2631, -0.7425,  1.9474],
         [ 0.2505,  0.1920, -0.6575,  0.7720, -1.8559],
         [-1.8510,  1.7704,  1.0231, -0.0032, -0.5381],
         [ 0.9023, -0.7329,  0.0700,  0.7111,  0.5866],
         [ 1.2204, -1.3466, -1.7060,  1.0389, -1.3278]]])

In [16]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])


In [17]:
batch_t = torch.randn(2,3,5,5) #batch, channel, rows, columns


In [18]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [21]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [23]:
a = torch.randn(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape
a_t

tensor([[ 0.4659, -0.2495, -0.0515],
        [ 0.8573, -0.9475,  1.1756]])